# Generated by Django 2.2.10 on 2020-02-26 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('type_desc', models.CharField(max_length=300)),
                ('active', models.IntegerField(default=1)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200)),
                ('plan_price', models.FloatField()),
                ('plan_benefits', models.TextField()),
                ('plan_duration', models.CharField(max_length=250)),
                ('max_users', models.ImageField(default=4, upload_to='')),
                ('blog_limit', models.ImageField(default=10, upload_to='')),
                ('active', models.IntegerField(default=1)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('support_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.SupportType')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('active', models.IntegerField(default=1)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('com_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='blog.Company')),
                ('plan_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='subscription.SubscriptionPlan')),
            ],
        ),
    ]
